/*
 * Groupe 4 
 * ANTHEA LATRUBESSE 
 * AURELIEN KOHL
 *  
 */
package Accueil;

import java.sql.Connection;

import java.sql.ResultSet;

import java.sql.Statement;

import javax.swing.JFrame;

//import com.sun.jndi.ldap.Connection;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import fonctionPSY.AjouterPatient;
import fonctionPSY.AjouterRendezvous;
import fonctionPSY.ListeConsultation;
import fonctionPSY.ListeConsultationX;
import fonctionPSY.ListePatient;
import fonctionPSY.ListeRDVall;
import fonctionPSY.NouvelleConsult;
import fonctionPSY.RDVancien;
import fonctionPSY.RDVfutur;
import fonctionPSY.RDVjourX;
import fonctionPSY.RDVsemaineX;

/**
 *
 * @author aurel
 */
public class AccueilPsy extends javax.swing.JFrame {

    private AjouterPatient AjoutPatient;
    //AjoutPatient = new AjouterPatient();
    //AjoutPatient.setVisible(true);

    private AjouterRendezvous AjoutRDV;
    //AjoutRDV = new AjouterRendezvous();
    //AjoutRDV.setVisible(true);

    private ListePatient listePatient;
    //listePatient = new ListePatient();
    //listePatient.setVisible(true);

    private ListeRDVall listeRDV;
    //listeRDV = new ListeRDVall();
    //listeRDV.setVisible(true);

    private RDVjourX RDVjourx;
    //RDVjourx = new RDVjourX();
    //RDVjourx.setVisible(true);

    private RDVsemaineX RDVsemainex;
    //RDVsemainex = new RDVsemaineX();
    //RDVsemainex.setVisible(true);
    private RDVfutur RDVFutur;
    //RDVFutur = new RDVfutur();
    //RDVFutur.setVisible(true);
    private RDVancien RDVAncien;
    //RDVAncien = new RDVancien();
    //RDVAncien.setVisible(true);

    private NouvelleConsult NewConsult;
    //NewConsult = new NouvelleConsult();
    //NewConsult.setVisible(true);

    private ListeConsultation listConsult;
    //listConsult = new ListeConsultation();
    //listConsult.setVisible(true);

    private ListeConsultationX listConsultX;
    //listConsultX = new ListeConsultationX();
    //listConsultX.setVisible(true);

    java.sql.Connection conn = null;

    String url = "jdbc:mysql://localhost/ProjetData30avrilV2";
    String login = "root";
    String passwd = "";
    Connection cn = null;
    Statement st = null;
    ResultSet rs = null;

    private JFrame frame;

    public AccueilPsy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonListePatient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonListeRendezVousAll = new javax.swing.JButton();
        jButtonAjoutPatient = new javax.swing.JButton();
        jButtonAjouterRDV = new javax.swing.JButton();
        jButtonConsult = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonListeRendezVousJour = new javax.swing.JButton();
        jButtonListeRendezVousProchain = new javax.swing.JButton();
        jButtonListeRendezVousSemaine = new javax.swing.JButton();
        jButtonListeRendezVousAncien = new javax.swing.JButton();
        jButtonConsult1 = new javax.swing.JButton();
        jButtonConsult2 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil Docteur");
        setMaximumSize(new java.awt.Dimension(370, 772));
        setMinimumSize(new java.awt.Dimension(370, 772));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 750));

        jButtonListePatient.setBackground(new java.awt.Color(153, 255, 204));
        jButtonListePatient.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonListePatient.setText("Voir Liste Patient");
        jButtonListePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListePatientActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setText("Interface Docteur");

        jButtonListeRendezVousAll.setBackground(new java.awt.Color(153, 255, 204));
        jButtonListeRendezVousAll.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonListeRendezVousAll.setText("Voir Liste Rendez Vous");
        jButtonListeRendezVousAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeRendezVousAllActionPerformed(evt);
            }
        });

        jButtonAjoutPatient.setBackground(new java.awt.Color(153, 255, 204));
        jButtonAjoutPatient.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonAjoutPatient.setText("Ajouter un Patient");
        jButtonAjoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutPatientActionPerformed(evt);
            }
        });

        jButtonAjouterRDV.setBackground(new java.awt.Color(153, 255, 204));
        jButtonAjouterRDV.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonAjouterRDV.setText("Ajouter un Rendez-Vous ");
        jButtonAjouterRDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterRDVActionPerformed(evt);
            }
        });

        jButtonConsult.setBackground(new java.awt.Color(153, 255, 204));
        jButtonConsult.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonConsult.setText("Lancer Consultation");
        jButtonConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setText("Gestion des patient :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setText("Gestion des rendez vous :");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel4.setText("Gestion des consultation : ");

        jButtonListeRendezVousJour.setBackground(new java.awt.Color(153, 255, 204));
        jButtonListeRendezVousJour.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonListeRendezVousJour.setText("Liste Rendez Vous Jour");
        jButtonListeRendezVousJour.setToolTipText("");
        jButtonListeRendezVousJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeRendezVousJourActionPerformed(evt);
            }
        });

        jButtonListeRendezVousProchain.setBackground(new java.awt.Color(153, 255, 204));
        jButtonListeRendezVousProchain.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonListeRendezVousProchain.setText("Liste prochain Rendez Vous ");
        jButtonListeRendezVousProchain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeRendezVousProchainActionPerformed(evt);
            }
        });

        jButtonListeRendezVousSemaine.setBackground(new java.awt.Color(153, 255, 204));
        jButtonListeRendezVousSemaine.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonListeRendezVousSemaine.setText("Liste Rendez Vous Semaine");
        jButtonListeRendezVousSemaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeRendezVousSemaineActionPerformed(evt);
            }
        });

        jButtonListeRendezVousAncien.setBackground(new java.awt.Color(153, 255, 204));
        jButtonListeRendezVousAncien.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonListeRendezVousAncien.setText("Liste ancien Rendez Vous ");
        jButtonListeRendezVousAncien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListeRendezVousAncienActionPerformed(evt);
            }
        });

        jButtonConsult1.setBackground(new java.awt.Color(153, 255, 204));
        jButtonConsult1.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonConsult1.setText("Voir toutes les Consultation");
        jButtonConsult1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsult1ActionPerformed(evt);
            }
        });

        jButtonConsult2.setBackground(new java.awt.Color(153, 255, 204));
        jButtonConsult2.setFont(new java.awt.Font("Yu Gothic", 2, 18)); // NOI18N
        jButtonConsult2.setText("Voir les Consultations d'un patient");
        jButtonConsult2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsult2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAjoutPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jButtonListeRendezVousAll, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListeRendezVousSemaine, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListeRendezVousAncien, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsult1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjouterRDV, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListeRendezVousJour, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListeRendezVousProchain, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsult2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButtonAjoutPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListePatient)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButtonAjouterRDV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonListeRendezVousAll)
                .addGap(18, 18, 18)
                .addComponent(jButtonListeRendezVousJour)
                .addGap(18, 18, 18)
                .addComponent(jButtonListeRendezVousSemaine)
                .addGap(18, 18, 18)
                .addComponent(jButtonListeRendezVousProchain)
                .addGap(18, 18, 18)
                .addComponent(jButtonListeRendezVousAncien)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsult)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsult1)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsult2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListeRendezVousAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeRendezVousAllActionPerformed
        listeRDV = new ListeRDVall();
        listeRDV.setVisible(true);
    }//GEN-LAST:event_jButtonListeRendezVousAllActionPerformed

    private void jButtonAjoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutPatientActionPerformed
        AjoutPatient = new AjouterPatient();
        AjoutPatient.setVisible(true);
    }//GEN-LAST:event_jButtonAjoutPatientActionPerformed

    private void jButtonListePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListePatientActionPerformed
        listePatient = new ListePatient();
        listePatient.setVisible(true);
    }//GEN-LAST:event_jButtonListePatientActionPerformed

    private void jButtonAjouterRDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterRDVActionPerformed
        AjoutRDV = new AjouterRendezvous();
        AjoutRDV.setVisible(true);
    }//GEN-LAST:event_jButtonAjouterRDVActionPerformed

    private void jButtonListeRendezVousJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeRendezVousJourActionPerformed
        RDVjourx = new RDVjourX();
        RDVjourx.setVisible(true);
    }//GEN-LAST:event_jButtonListeRendezVousJourActionPerformed

    private void jButtonListeRendezVousSemaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeRendezVousSemaineActionPerformed
        RDVsemainex = new RDVsemaineX();
        RDVsemainex.setVisible(true);
    }//GEN-LAST:event_jButtonListeRendezVousSemaineActionPerformed

    private void jButtonListeRendezVousProchainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeRendezVousProchainActionPerformed
        RDVFutur = new RDVfutur();
        RDVFutur.setVisible(true);
    }//GEN-LAST:event_jButtonListeRendezVousProchainActionPerformed

    private void jButtonListeRendezVousAncienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListeRendezVousAncienActionPerformed
        RDVAncien = new RDVancien();
        RDVAncien.setVisible(true);
    }//GEN-LAST:event_jButtonListeRendezVousAncienActionPerformed

    private void jButtonConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultActionPerformed
        NewConsult = new NouvelleConsult();
        NewConsult.setVisible(true);
    }//GEN-LAST:event_jButtonConsultActionPerformed

    private void jButtonConsult1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsult1ActionPerformed
        listConsult = new ListeConsultation();
        listConsult.setVisible(true);
    }//GEN-LAST:event_jButtonConsult1ActionPerformed

    private void jButtonConsult2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsult2ActionPerformed
        listConsultX = new ListeConsultationX();
        listConsultX.setVisible(true);
    }//GEN-LAST:event_jButtonConsult2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilPsy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilPsy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilPsy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilPsy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilPsy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAjoutPatient;
    private javax.swing.JButton jButtonAjouterRDV;
    private javax.swing.JButton jButtonConsult;
    private javax.swing.JButton jButtonConsult1;
    private javax.swing.JButton jButtonConsult2;
    private javax.swing.JButton jButtonListePatient;
    private javax.swing.JButton jButtonListeRendezVousAll;
    private javax.swing.JButton jButtonListeRendezVousAncien;
    private javax.swing.JButton jButtonListeRendezVousJour;
    private javax.swing.JButton jButtonListeRendezVousProchain;
    private javax.swing.JButton jButtonListeRendezVousSemaine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
