/*
 * Groupe 4 
 * ANTHEA LATRUBESSE 
 * AURELIEN KOHL
 *  
 */
package fonctionPSY;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aurel
 */
public class ListeConsultation extends javax.swing.JFrame {

    java.sql.Connection conn = null;

    String url = "jdbc:mysql://localhost/ProjetData30avrilV2";
    String login = "root";
    String passwd = "";
    Connection cn = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * Creates new form ListeConsultation
     */
    public ListeConsultation() {
        initComponents();
        afficherList();
    }
//RDVlist = ConsultList
    // rdvList = CONSULTlist

    public ArrayList<ConsultList> CONSULTlist() {
        ArrayList<ConsultList> CONSULTlist = new ArrayList<>();
        try {

            conn = DriverManager.getConnection(url, login, passwd);
            st = (Statement) conn.createStatement();
            rs = st.executeQuery("SELECT  A.identifiant_patient, A.nom_patient, A.prenom_patient, C.identifiant_RendezVous, C.Type_RendezVous, D.Date_Consultation, D.Heure_Consultation, D.Duree_Consultation, D.identifiant_Consultation, D.Notes_Consultation, D.Anxiete_Consultation, D.Prix_Consultation, D.Paiement_Consultation\n"
                    + "FROM patient A, concerner B, rendezvous C, consultation D\n"
                    + "WHERE A.identifiant_patient=B.identifiant_patient\n"
                    + "AND B.identifiant_RendezVous=C.identifiant_RendezVous\n"
                    + "AND C.identifiant_consultation = D.identifiant_consultation");

            ConsultList CONSULTLIST;  //CONSULTLIST

            while (rs.next()) {
                CONSULTLIST = new ConsultList(rs.getInt("Identifiant_patient"), rs.getInt("Identifiant_RendezVous"), rs.getInt("Identifiant_Consultation"), rs.getString("Nom_patient"), rs.getString("Prenom_patient"), rs.getString("Type_RendezVous"), rs.getString("Date_Consultation"), rs.getString("Heure_Consultation"), rs.getString("Duree_Consultation"), rs.getString("Notes_Consultation"), rs.getString("Anxiete_Consultation"), rs.getString("Prix_Consultation"), rs.getString("Paiement_Consultation"));
                CONSULTlist.add(CONSULTLIST);

            }

        } catch (SQLException ex) {
            Logger.getLogger(ListeConsultation.class.getName()).log(Level.SEVERE, null, ex);
        }
        return CONSULTlist;

    }

    public void afficherList() {
        ArrayList<ConsultList> list = CONSULTlist();
        DefaultTableModel model = (DefaultTableModel) jTableConsult.getModel();
        Object[] row = new Object[13];
        for (int i = 0; i < list.size(); i++) {

            row[0] = list.get(i).getIdentifiant_patient(); //rs.getInt("Identifiant_patient")
            row[1] = list.get(i).getNom_patient(); //rs.getString("Nom_patient")
            row[2] = list.get(i).getPrenom_patient(); //rs.getString("Prenom_patient")
            row[3] = list.get(i).getIdentifiant_RendezVous(); //rs.getInt("Identifiant_RendezVous")
            row[4] = list.get(i).getType_RendezVous(); //rs.getString("Type_RendezVous")
            row[5] = list.get(i).getDate_Consultation(); //rs.getString("Date_Consultation")
            row[6] = list.get(i).getHeure_Consultation(); //rs.getString("Heure_Consultation"), rs.getString("Duree_Consultation"), rs.getInt("Identifiant_Consultation"), rs.getString("Notes_Consultation"),rs.getString("Anxiete_Consultation"),rs.getString("Prix_Consultation"),rs.getString("Paiement_Consultation")
            row[7] = list.get(i).getDuree_Consultation(); 
            row[8] = list.get(i).getIdentifiant_Consultation(); //rs.getInt("Identifiant_Consultation")
            row[9] = list.get(i).getNotes_Consultation(); //rs.getString("Notes_Consultation")
            row[10] = list.get(i).getAnxiete_Consultation(); //rs.getString("Anxiete_Consultation")
            row[11] = list.get(i).getPrix_Consultation(); //rs.getString("Prix_Consultation")
            row[12] = list.get(i).getPaiement_Consultation(); //rs.getString("Paiement_Consultation")

            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 550));
        setMinimumSize(new java.awt.Dimension(1000, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liste des consultations enregistrées :");

        jTableConsult.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        jTableConsult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Patient", "Nom", "Prenom", "ID RDV", "Type ", "Date", "Heure", "Durée", "ID Consult", "Notes", "Anxiété", "Prix", "Paiement"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableConsult.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTableConsult);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeConsultation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsult;
    // End of variables declaration//GEN-END:variables
}
