/*
 * Groupe 4 
 * ANTHEA LATRUBESSE 
 * AURELIEN KOHL
 *  
 */
package fonctionPSY;

import fonctionPatient.InfoPatientX;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aurel
 */
public class NouvelleConsult extends javax.swing.JFrame {

    java.sql.Connection conn = null;

    String url = "jdbc:mysql://localhost/ProjetData30avrilV2";
    String login = "root";
    String passwd = "";
    Connection cn = null;
    Statement st = null;
    ResultSet rs = null;

    private int miliseconds = 0;
    private int second = 0;
    private int minutes = 0;
    private int hours = 0;
    private boolean statut = true;

    private InfoPatientX INFOpatient;

    public NouvelleConsult() {
        initComponents();
        afficherList();
    }

    public ArrayList<RDVlist> rdvList() {
        ArrayList<RDVlist> rdvList = new ArrayList<>();
        try {
            //recuperation de la date du jour 
            LocalDate Today = (LocalDate.now());
            System.out.println(Today);

            conn = DriverManager.getConnection(url, login, passwd);
            st = (Statement) conn.createStatement();
            rs = st.executeQuery("SELECT A.identifiant_patient, A.nom_patient, A.prenom_patient, c.Date_RendezVous, C.Heure_RendezVous, c.Type_RendezVous, C.identifiant_RendezVous \n"
                    + "from patient A, concerner B, rendezvous C \n"
                    + "WHERE A.identifiant_patient=B.identifiant_patient \n"
                    + "AND B.identifiant_RendezVous=C.identifiant_RendezVous "
                    + "AND Date_RendezVous = '" + Today + "' "
                    + "ORDER BY `Date_RendezVous` ASC ;");
            RDVlist RDVX;

            while (rs.next()) {
                RDVX = new RDVlist(rs.getInt("identifiant_patient"),rs.getString("nom_patient"), rs.getString("prenom_patient"), rs.getString("Date_RendezVous"), rs.getString("Heure_RendezVous"), rs.getString("Type_RendezVous"), rs.getInt("identifiant_RendezVous"));
                rdvList.add(RDVX);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NouvelleConsult.class.getName()).log(Level.SEVERE, null, ex);
        }
        return rdvList;

    }

    public void afficherList() {
        ArrayList<RDVlist> list = rdvList();
        DefaultTableModel model = (DefaultTableModel) jTableRDV.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getIdentifiant_patient();
            row[1] = list.get(i).getNom_patient();
            row[2] = list.get(i).getPrenom_patient();
            row[3] = list.get(i).getDate_RendezVous();
            row[4] = list.get(i).getHeure_RendezVous();
            row[5] = list.get(i).getType_RendezVous();
            row[6]= list.get(i).getIdentifiant_RendezVous();
            
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLabelMinute = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JLabelSecond = new javax.swing.JLabel();
        JLabelMilisecond = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNotes = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonTerminer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSliderAnxiete = new javax.swing.JSlider();
        jLabelHeureDebut = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRDV = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxAxiete = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldPrix = new javax.swing.JTextField();
        JLabelHour = new javax.swing.JLabel();
        jComboBoxPaiement = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(659, 620));
        setMinimumSize(new java.awt.Dimension(659, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        JLabelMinute.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        JLabelMinute.setText("Minutes");

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        jLabel11.setText("Moyen de paiement :");

        JLabelSecond.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        JLabelSecond.setText("Secondes");

        JLabelMilisecond.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        JLabelMilisecond.setText("Milisecondes");

        jTextAreaNotes.setColumns(20);
        jTextAreaNotes.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jTextAreaNotes.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNotes);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Yu Gothic Medium", 2, 11)); // NOI18N
        jButton2.setText("Arrêter Timer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("€");

        jLabel8.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        jLabel8.setText("Notes de la consultation :");

        jButtonTerminer.setBackground(new java.awt.Color(102, 255, 102));
        jButtonTerminer.setFont(new java.awt.Font("Yu Gothic Medium", 3, 36)); // NOI18N
        jButtonTerminer.setText("Terminer");
        jButtonTerminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nouvelle Consultation :  ");

        jSliderAnxiete.setBackground(new java.awt.Color(255, 255, 255));
        jSliderAnxiete.setMaximum(10);

        jLabelHeureDebut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        jLabelHeureDebut.setText("heure debut");

        jTableRDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "identifiant ", "Nom", "Prenom", "Date", "Heure", "Type", "N° Rendez Vous"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableRDV);

        jLabel9.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        jLabel9.setText("Niveau d'anxiete : ");

        jLabel4.setText("0");

        jCheckBoxAxiete.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxAxiete.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        jCheckBoxAxiete.setText("Cocher si axiété puis doser ");
        jCheckBoxAxiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAxieteActionPerformed(evt);
            }
        });

        jLabel5.setText("10");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        jLabel2.setText("Choisir le Rendez vous concerné par la consultation :");

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        jLabel10.setText("Prix de la séance : ");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 2, 11)); // NOI18N
        jButton1.setText("Lancer le chrono");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldPrix.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        jTextFieldPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrixActionPerformed(evt);
            }
        });

        JLabelHour.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        JLabelHour.setText("Heures");

        jComboBoxPaiement.setFont(new java.awt.Font("Yu Gothic Light", 0, 11)); // NOI18N
        jComboBoxPaiement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especes", "Cheque", "Carte Bleu" }));
        jComboBoxPaiement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaiementActionPerformed(evt);
            }
        });

        jButton3.setText("Infos Patient");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTerminer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPrix)
                                    .addComponent(jComboBoxPaiement, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxAxiete)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSliderAnxiete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton1)
                                            .addGap(39, 39, 39)
                                            .addComponent(JLabelHour)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(JLabelMinute)
                                            .addGap(17, 17, 17)
                                            .addComponent(JLabelSecond)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(JLabelMilisecond)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabelHeureDebut))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 20, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(JLabelSecond)
                    .addComponent(JLabelMinute)
                    .addComponent(JLabelHour)
                    .addComponent(JLabelMilisecond)
                    .addComponent(jButton2)
                    .addComponent(jLabelHeureDebut))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jCheckBoxAxiete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderAnxiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxPaiement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTerminer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DateFormat format = new SimpleDateFormat("HH:mm:ss");
        Calendar HEUREDEBUT = Calendar.getInstance();
        System.out.println(format.format(HEUREDEBUT.getTime()));
        jLabelHeureDebut.setText(format.format(HEUREDEBUT.getTime()));

        statut = true;
        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    if (statut == true) {
                        try {
                            sleep(1);
                            if (miliseconds > 500) {
                                miliseconds = 0;
                                second++;

                            }
                            if (second > 60) {
                                second = 0;
                                minutes++;

                            }
                            if (minutes > 60) {
                                miliseconds = 0;
                                second = 0;
                                minutes = 0;
                                hours++;

                            }
                            JLabelMilisecond.setText(":" + miliseconds * 2);
                            miliseconds++;
                            JLabelSecond.setText("" + second);
                            JLabelMinute.setText("" + minutes + ":");
                            JLabelHour.setText("" + hours + ":");

                        } catch (Exception e) {

                        }
                    } else {
                        break;
                    }
                }
            }

        };
        t.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxAxieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAxieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAxieteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        statut = false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrixActionPerformed

    private void jButtonTerminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminerActionPerformed
        statut = false;
        //recup identifiant rdv 
        int ligne1 = jTableRDV.getSelectedRow();//ligne du patient
        int colonne1 = 6;//colone identifiant
        int IDrdv = (int) jTableRDV.getValueAt(ligne1, colonne1);
        System.out.println("l'identifiant du rdv selectionné est : " + IDrdv);

        //recup date 
        LocalDate Today = (LocalDate.now());
        System.out.println(Today);
        LocalDate Date = Today;
        System.out.println("date " + Date);

        //recup dure 
        String dure = JLabelHour.getText() + JLabelMinute.getText() + JLabelSecond.getText();

        System.out.println("durée :  " + dure);

        //recup heure
        String heure = jLabelHeureDebut.getText();
        System.out.println("heure debut : " + heure);

        //recup note
        String Notes = jTextAreaNotes.getText();

        String LVLanxiete2 = "NULL";

        if (jCheckBoxAxiete.isSelected()) {
            int LVLanxiete = jSliderAnxiete.getValue();
            LVLanxiete2 = "'"+Integer.toString(LVLanxiete)+"'";
        }

        //recup prix 
        String prix = jTextFieldPrix.getText();

        //recup moyen de paiement 
        String MoyenPaiment = (String) jComboBoxPaiement.getSelectedItem();

        try {
            conn = DriverManager.getConnection(url, login, passwd);
            st = (Statement) conn.createStatement();
//INSERT INTO `consultation` (`identifiant_Consultation`, `identifiant_RendezVous`, `Date_Consultation`, `Heure_Consultation`, `Duree_Consultation`, `Notes_Consultation`, `Anxiete_Consultation`, `Prix_Consultation`, `Paiement_Consultation`) VALUES (NULL, '19', '2020-05-30', '08:04:12', '00:24:19', 'rien de special \r\ntout se passe bien ', '5', '35', 'Carte Bleu');
            st.executeUpdate("INSERT INTO `consultation` (`identifiant_Consultation`, `identifiant_RendezVous`, `Date_Consultation`, `Heure_Consultation`, `Duree_Consultation`, `Notes_Consultation`, `Anxiete_Consultation`, `Prix_Consultation`, `Paiement_Consultation`) "
                    + "VALUES (NULL, '" + IDrdv + "', '" + Date + "', '" + heure + "', '" + dure + "', '" + Notes + " ', " + LVLanxiete2 + ", '" + prix + "', '" + MoyenPaiment + "');");

            JOptionPane.showMessageDialog(null, "Creation Consultation Terminé ", "Ajout Consult", JOptionPane.INFORMATION_MESSAGE);

            int idConsult = recupIDconsult();

            try {
                conn = DriverManager.getConnection(url, login, passwd);
                st = (Statement) conn.createStatement();
//INSERT INTO `consultation` (`identifiant_Consultation`, `identifiant_RendezVous`, `Date_Consultation`, `Heure_Consultation`, `Duree_Consultation`, `Notes_Consultation`, `Anxiete_Consultation`, `Prix_Consultation`, `Paiement_Consultation`) VALUES (NULL, '19', '2020-05-30', '08:04:12', '00:24:19', 'rien de special \r\ntout se passe bien ', '5', '35', 'Carte Bleu');
                st.executeUpdate("UPDATE `rendezvous` SET `identifiant_Consultation` = '" + idConsult + "' WHERE `rendezvous`.`identifiant_RendezVous` = " + IDrdv + ";");

                JOptionPane.showMessageDialog(null, "lien Consultation Terminé ", "Ajout lien Consult", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException ex) {
                Logger.getLogger(NouvelleConsult.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(NouvelleConsult.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonTerminerActionPerformed

    int recupIDconsult() {

        int identifiantTrouve = 0;

        try {

            conn = DriverManager.getConnection(url, login, passwd);
            st = (Statement) conn.createStatement();
            rs = st.executeQuery("SELECT * FROM `consultation` "
                    + "ORDER BY `identifiant_Consultation` ASC");

            while (rs.next()) {
                //on descend a la derniere ligne ajouté
                identifiantTrouve = rs.getInt("identifiant_Consultation");
            }

        } catch (SQLException ex) {
            Logger.getLogger(NouvelleConsult.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("l'identifiant de la consult crée est " + identifiantTrouve);
        return identifiantTrouve;
    }


    private void jComboBoxPaiementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaiementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPaiementActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int ligne1 = jTableRDV.getSelectedRow();//ligne du patient
        int colonne1 = 0;//colone identifiant
        int IDpatient = (int) jTableRDV.getValueAt(ligne1, colonne1);
        System.out.println("l'identifiant du patient selectionné est : " + IDpatient);
        INFOpatient = new InfoPatientX(IDpatient);
        INFOpatient.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouvelleConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouvelleConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouvelleConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouvelleConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NouvelleConsult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelHour;
    private javax.swing.JLabel JLabelMilisecond;
    private javax.swing.JLabel JLabelMinute;
    private javax.swing.JLabel JLabelSecond;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonTerminer;
    private javax.swing.JCheckBox jCheckBoxAxiete;
    private javax.swing.JComboBox<String> jComboBoxPaiement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHeureDebut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderAnxiete;
    private javax.swing.JTable jTableRDV;
    private javax.swing.JTextArea jTextAreaNotes;
    private javax.swing.JTextField jTextFieldPrix;
    // End of variables declaration//GEN-END:variables
}
